audio
IgorValov/MusicHost pull request #1
Opened 2022-10-11 17:27 UTC by IgorValov

2022-10-12 07:17 UTC, mrerberg requested changes

2022-10-12 07:17 UTC, mrerberg commented on src/components/main/nav/nav.js
> +// import classNames from "classnames";
?

2022-10-12 07:17 UTC, mrerberg commented on src/registrer/register.jsx
> +  const LoginReg = "login input__reg ";
Зачем существуют данные переменные?

2022-10-12 07:17 UTC, mrerberg commented on src/routes.jsx
>  // import { Link } from "react-router-dom";
?

2022-10-12 07:17 UTC, mrerberg commented on package.json
> +    "classnames": "^2.3.2",
Зачем тебе данная либа, если ты ее не используешь?

2022-10-13 10:00 UTC, IgorValov commented on package.json
> +    "classnames": "^2.3.2",
ну она была нужна , потом обошелся без нее и если пригодится оставил

2022-10-13 10:00 UTC, IgorValov commented on src/routes.jsx
>  // import { Link } from "react-router-dom";
это я убрал

2022-10-13 10:04 UTC, IgorValov commented on src/components/main/nav/nav.js
> +// import classNames from "classnames";
убрал, просто на всякий случай  для себя оставлял

2022-10-14 07:36 UTC, mrerberg requested changes

2022-10-14 07:36 UTC, mrerberg commented on package.json
> +    "classnames": "^2.3.2",
Не используешь - удаляй, потом пригодиться - поставишь

2022-10-14 07:36 UTC, mrerberg commented on src/ToggleTheme/page/index.jsx
> +//Принимает в себя функцию, и он будет меняться по нажатию на theme-switcher
?

2022-10-14 07:36 UTC, mrerberg commented on src/ToggleTheme/theme-switcher/index.jsx
> +//Переключатель темы
?

2022-10-14 07:36 UTC, mrerberg commented on src/components/container/main/nav/nav.js
> +  const ClickBurger = () => {
Почему с большой буквы?

2022-10-14 07:36 UTC, mrerberg commented on src/components/container/main/nav/nav.js
> +  const BurgerLineStyle = { backgroundColor: theme.color, color: theme.color };
Почему с большой буквы?

2022-10-14 07:36 UTC, mrerberg commented on src/registrer/register.jsx
> +  const LoginReg = "login input__reg ";
Не вижу, чтобы убрал

2022-10-14 07:46 UTC, IgorValov commented on src/registrer/register.jsx
> +  const LoginReg = "login input__reg ";
та я другой коммит создал

2022-10-14 10:45 UTC, closed without merging